# Generated by Django 4.2.7 on 2025-04-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='a', upload_to='services/'),
            preserve_default=False,
        ),
    ]
