# Generated by Django 5.2 on 2025-04-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contato',
            field=models.BooleanField(default=False, help_text='Ativar formulário de contato?', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default=1, help_text='Email para contato', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
