# Generated by Django 4.2.7 on 2025-04-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='detalheproduto',
            name='quantidade_produto',
        ),
        migrations.RemoveField(
            model_name='detalheproduto',
            name='subsetor',
        ),
        migrations.RemoveField(
            model_name='subsector',
            name='quantidade',
        ),
        migrations.CreateModel(
            name='DetalheProdutoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkCaminho', models.CharField(max_length=100)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_det', to='app.detalheproduto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhess', to='app.detalheproduto')),
                ('id_subsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsetor', to='app.subsector')),
            ],
        ),
    ]
