# Generated by Django 5.2 on 2025-04-19 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da aba', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Abas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da empresa', max_length=100, verbose_name='Nome')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/static/images/', verbose_name='Logo')),
                ('bg_logo', models.FileField(blank=True, help_text='Aceita imagens ou vídeos', null=True, upload_to='empresa/static/media/', verbose_name='Imagem ou Vídeo de Fundo')),
                ('sobre', models.CharField(help_text='Texto que descreve a empresa', max_length=255, verbose_name='Sobre')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
        migrations.CreateModel(
            name='AbaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do item da aba', max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(help_text='Descrição do item da aba', max_length=255, verbose_name='Descrição')),
                ('imagem', models.ImageField(help_text='Imagem do Item', upload_to='empresa/static/images/', verbose_name='Imagem')),
                ('aba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='empresa.aba', verbose_name='Aba')),
            ],
            options={
                'verbose_name': 'Item de Aba',
                'verbose_name_plural': 'Itens de Aba',
            },
        ),
        migrations.AddField(
            model_name='aba',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abas', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da rede social', max_length=100, verbose_name='Nome')),
                ('link', models.CharField(help_text='Link da rede social', max_length=255, verbose_name='Link')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redes_sociais', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
    ]
